/* Exercício Livraria*/
CREATE DATABASE LIVRARIA;
USE LIVRARIA;
CREATE TABLE LIVROS(
	LIVRO VARCHAR(100),
	AUTOR VARCHAR(100),
	SEXO CHAR(1),
	PAGINAs INT(5),
	EDITORA VARCHAR(30),
	VALOR FLOAT(10,2),
	UF CHAR(2),
	ANO INT(4)
);

INSERT INTO LIVROS VALUES('Cavaleiro Real','Ana Claudia','F',465,'Atlas',49.9,'RJ',2009);
INSERT INTO LIVROS VALUES('SQL para leigos','João Nunes','M',450,'Addison',98,'SP',2018);
INSERT INTO LIVROS VALUES('Receitas Caseiras','Celia Tavares','F',210,'Atlas',45,'RJ',2008);
INSERT INTO LIVROS VALUES('Pessoas Efetivas','Eduardo Santos','M',390,'Beta',78.99,'RJ',2018);
INSERT INTO LIVROS VALUES('Habitos Saudáveis','Eduardo Santos','M',630,'Beta',150.98,'RJ',2019);
INSERT INTO LIVROS VALUES('A Casa Marrom','Hermes Macedo','M',250,'Bubba',60,'MG',2016);
INSERT INTO LIVROS VALUES('Estacio Querido','Geraldo Francisco','M',310,'Insignia',100,'ES',2015);
INSERT INTO LIVROS VALUES('Pra sempre amigas','Leda Silva','F',510,'Insignia',78.98,'ES',2011);
INSERT INTO LIVROS VALUES('Copas Inesqueciveis','Marco Alcantara','M',200,'Larson',130.98,'RS',2018);
INSERT INTO LIVROS VALUES('O poder da mente','Clara Mafra','F',120,'Continental',56.58,'SP',2017);

/* 1) TRAZER TODOS OS DADOS */

SELECT * FROM LIVROS;

/* 2) TRAZER O NOME DO LIVRO E O NOME DA EDITORA */
 
SELECT NOME_DO_LIVRO, NOME_DA_EDITORA FROM LIVROS;

/* 3) TRAZER O NOME DO LIVRO E A UF DOS LIVROS PUBLICADOS POR AUTORES DO SEXO MASCULINO */

SELECT NOME_DO_LIVRO, ESTADO_UF_DA_EDITORA FROM LIVROS WHERE SEXO_DO_AUTOR = 'Masculino';

/* 4) TRAZER O NOME DO LIVRO E O NUMERO DE PAGINAS DOS LIVROS POR AUTORES DO SEXO FEMENINO */

SELECT NOME_DO_LIVRO, NUMERO_DE_PÁGINAS FROM LIVROS WHERE SEXO_DO_AUTOR = 'Feminino';

/* 5) TRAZER OS VALORES DOS LIVROS DAS EDITORAS DE SAO PAULO */

SELECT VALOR_DO_LIVRO FROM LIVROS WHERE ESTADO_UF_DA_EDITORA = 'SP';

/* 6) TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS POR SAO PAULO E RIO DE JANEIRO */

SELECT NOME_DO_AUTOR FROM LIVROS WHERE (ESTADO_UF_DA_EDITORA = 'SP' OR ESTADO_UF_DA_EDITORA = 'RJ') AND SEXO_DO_AUTOR='Masculino'; 


